FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

# 1. Install system dependencies as root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        fonts-freefont-ttf=20120503-10 \
    && rm -rf /var/lib/apt/lists/*

# correct mapping to make libvips work
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7

# install libvips
RUN apt-get update \
    && apt-get install -y libvips libvips-dev libvips-tools libtiff5-dev

# install default fonts
RUN apt-get install -y fonts-freefont-ttf

# 2. Create user
RUN useradd -m -u 1000 pipelineuser

# 3. Setup work area
WORKDIR /home/pipelineuser

# 4. Copy requirements AND change ownership so the user can read it
COPY --chown=pipelineuser:pipelineuser requirements.txt .

# 5. Switch user
USER pipelineuser

# 6. Update PATH so the user-installed pip/packages are found
ENV PATH="/home/pipelineuser/.local/bin:${PATH}"

# 7. Install Python packages
RUN pip install --upgrade pip && \
    grep -E 'aind-data-schema|aind-metadata-upgrader|aind-qcportal-schema|pyvips|wavpack-numcodecs|pynwb|hdmf-zarr|torch|hdbscan|s3fs|seaborn|scikit-learn|neo|scipy' requirements.txt | xargs pip install

# 8. Extract the spikeinterface version and install with extras
RUN pip install --upgrade pip && \
    SPIKEINTERFACE_VERSION=$(grep '^spikeinterface==' requirements.txt | cut -d'=' -f3) && \
    pip install "spikeinterface[full,widgets]==${SPIKEINTERFACE_VERSION}"